from random import randint
import ctypes
import pygame

#SCREEN
user32 = ctypes.windll.user32
SCREEN_WIDTH, SCREEN_HEIGHT = user32.GetSystemMetrics(0), user32.GetSystemMetrics(1)

SET_1 = pygame.FULLSCREEN
SET_2 = pygame.RESIZABLE

HP_LINE_HEIGHT = 30
HP_CHANGE = 100

#ZOMBIE
ZOMBIE_STEP = 15
ZOMBIE_HEALTH = 60
ZOMBIE_ANGLE = 180
ZOMBIE_FRAME_COUNT = 0
ZOMBIE_ANIM_ATTACK = 8
ZOMBIE_ANIM_MOVE = 28
ZOMBIE_DAMAGE = 1

MAX_BLOOD = 10
DIFICULTY = 1
DELAY = 50
SPAWN_POINT = []
COUNT_OF_ZOMBIES = 10
for i in range(COUNT_OF_ZOMBIES):
    SPAWN_POINT.append((SCREEN_WIDTH, randint(0, SCREEN_HEIGHT - 210)))

#MAN
MAN_STEP = 5
MAN_HEALTH = 100
MAN_ANGLE = 180
MAN_FRAME_COUNT = 0
MAN_ANIM_MOVE = 35
MAN_ANIM_RELOAD = 27
MAN_BULLETS = 10
MAN_DAMAGE = 30

MAN_SCORE_COLOR = (0, 0, 0)
MAN_SCORE_TEXT = "SCORE: "
MAN_SCORE_TEXT_SIZE = 40

#MENU
FONT = 'fonts\\font_2.ttf'
TEXT_COLOR = (31, 30, 30)
TEXT_COLOR_CHOOSE = (217, 127, 9)
FONT_SIZE = 150
TEXT_1 = "PLAY"
TEXT_2 = "EXIT"

#GAMEOVER
TIMER = 300
FONT_SIZE_GO = 150
TEXT_GO = "GAME OVER"
